// Code generated by hertz generator.

package user

import (
	"github.com/Tracy-coder/e-mall/biz/handler/middleware"
	"github.com/Tracy-coder/e-mall/configs"
	"github.com/Tracy-coder/e-mall/data"
	"github.com/cloudwego/hertz/pkg/app"
)

func rootMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _apiMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _v1Mw() []app.HandlerFunc {
	// your code...
	return nil
}

func _captchaMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _registerMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _verifyemailMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _githubMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _loginMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _gtloginMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _gtlogincallbackMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _userMw() []app.HandlerFunc {
	// your code...
	return []app.HandlerFunc{middleware.GetJWTMiddleware(configs.Data(), data.Default()).MiddlewareFunc()}
}

func _userinfoMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _validemailMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _v2Mw() []app.HandlerFunc {
	// your code...
	return nil
}

func _createproductMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _showproductMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _listproductMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _updateproductMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _deleteproductMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _createcategoryMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _listcategoryMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _listcarouselsMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _createcarouselMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _uploadavatarMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _productMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _showproductimgMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _product0Mw() []app.HandlerFunc {
	// your code...
	return nil
}

func _createproductimgMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _showproductrankingsMw() []app.HandlerFunc {
	// your code...
	return nil
}
