// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Tracy-coder/e-mall/data/ent/cart"
	"github.com/Tracy-coder/e-mall/data/ent/product"
	"github.com/Tracy-coder/e-mall/data/ent/user"
)

// CartCreate is the builder for creating a Cart entity.
type CartCreate struct {
	config
	mutation *CartMutation
	hooks    []Hook
}

// SetCreatedAt sets the "created_at" field.
func (cc *CartCreate) SetCreatedAt(t time.Time) *CartCreate {
	cc.mutation.SetCreatedAt(t)
	return cc
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (cc *CartCreate) SetNillableCreatedAt(t *time.Time) *CartCreate {
	if t != nil {
		cc.SetCreatedAt(*t)
	}
	return cc
}

// SetUpdatedAt sets the "updated_at" field.
func (cc *CartCreate) SetUpdatedAt(t time.Time) *CartCreate {
	cc.mutation.SetUpdatedAt(t)
	return cc
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (cc *CartCreate) SetNillableUpdatedAt(t *time.Time) *CartCreate {
	if t != nil {
		cc.SetUpdatedAt(*t)
	}
	return cc
}

// SetUserID sets the "UserID" field.
func (cc *CartCreate) SetUserID(u uint64) *CartCreate {
	cc.mutation.SetUserID(u)
	return cc
}

// SetNillableUserID sets the "UserID" field if the given value is not nil.
func (cc *CartCreate) SetNillableUserID(u *uint64) *CartCreate {
	if u != nil {
		cc.SetUserID(*u)
	}
	return cc
}

// SetProductID sets the "ProductID" field.
func (cc *CartCreate) SetProductID(u uint64) *CartCreate {
	cc.mutation.SetProductID(u)
	return cc
}

// SetNillableProductID sets the "ProductID" field if the given value is not nil.
func (cc *CartCreate) SetNillableProductID(u *uint64) *CartCreate {
	if u != nil {
		cc.SetProductID(*u)
	}
	return cc
}

// SetNum sets the "Num" field.
func (cc *CartCreate) SetNum(i int32) *CartCreate {
	cc.mutation.SetNum(i)
	return cc
}

// SetMaxNum sets the "MaxNum" field.
func (cc *CartCreate) SetMaxNum(i int32) *CartCreate {
	cc.mutation.SetMaxNum(i)
	return cc
}

// SetCheck sets the "Check" field.
func (cc *CartCreate) SetCheck(b bool) *CartCreate {
	cc.mutation.SetCheck(b)
	return cc
}

// SetID sets the "id" field.
func (cc *CartCreate) SetID(u uint64) *CartCreate {
	cc.mutation.SetID(u)
	return cc
}

// SetUserCartID sets the "user_cart" edge to the User entity by ID.
func (cc *CartCreate) SetUserCartID(id uint64) *CartCreate {
	cc.mutation.SetUserCartID(id)
	return cc
}

// SetNillableUserCartID sets the "user_cart" edge to the User entity by ID if the given value is not nil.
func (cc *CartCreate) SetNillableUserCartID(id *uint64) *CartCreate {
	if id != nil {
		cc = cc.SetUserCartID(*id)
	}
	return cc
}

// SetUserCart sets the "user_cart" edge to the User entity.
func (cc *CartCreate) SetUserCart(u *User) *CartCreate {
	return cc.SetUserCartID(u.ID)
}

// SetProductCartID sets the "product_cart" edge to the Product entity by ID.
func (cc *CartCreate) SetProductCartID(id uint64) *CartCreate {
	cc.mutation.SetProductCartID(id)
	return cc
}

// SetNillableProductCartID sets the "product_cart" edge to the Product entity by ID if the given value is not nil.
func (cc *CartCreate) SetNillableProductCartID(id *uint64) *CartCreate {
	if id != nil {
		cc = cc.SetProductCartID(*id)
	}
	return cc
}

// SetProductCart sets the "product_cart" edge to the Product entity.
func (cc *CartCreate) SetProductCart(p *Product) *CartCreate {
	return cc.SetProductCartID(p.ID)
}

// Mutation returns the CartMutation object of the builder.
func (cc *CartCreate) Mutation() *CartMutation {
	return cc.mutation
}

// Save creates the Cart in the database.
func (cc *CartCreate) Save(ctx context.Context) (*Cart, error) {
	cc.defaults()
	return withHooks(ctx, cc.sqlSave, cc.mutation, cc.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (cc *CartCreate) SaveX(ctx context.Context) *Cart {
	v, err := cc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (cc *CartCreate) Exec(ctx context.Context) error {
	_, err := cc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (cc *CartCreate) ExecX(ctx context.Context) {
	if err := cc.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (cc *CartCreate) defaults() {
	if _, ok := cc.mutation.CreatedAt(); !ok {
		v := cart.DefaultCreatedAt()
		cc.mutation.SetCreatedAt(v)
	}
	if _, ok := cc.mutation.UpdatedAt(); !ok {
		v := cart.DefaultUpdatedAt()
		cc.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (cc *CartCreate) check() error {
	if _, ok := cc.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "Cart.created_at"`)}
	}
	if _, ok := cc.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "Cart.updated_at"`)}
	}
	if _, ok := cc.mutation.Num(); !ok {
		return &ValidationError{Name: "Num", err: errors.New(`ent: missing required field "Cart.Num"`)}
	}
	if _, ok := cc.mutation.MaxNum(); !ok {
		return &ValidationError{Name: "MaxNum", err: errors.New(`ent: missing required field "Cart.MaxNum"`)}
	}
	if _, ok := cc.mutation.Check(); !ok {
		return &ValidationError{Name: "Check", err: errors.New(`ent: missing required field "Cart.Check"`)}
	}
	return nil
}

func (cc *CartCreate) sqlSave(ctx context.Context) (*Cart, error) {
	if err := cc.check(); err != nil {
		return nil, err
	}
	_node, _spec := cc.createSpec()
	if err := sqlgraph.CreateNode(ctx, cc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != _node.ID {
		id := _spec.ID.Value.(int64)
		_node.ID = uint64(id)
	}
	cc.mutation.id = &_node.ID
	cc.mutation.done = true
	return _node, nil
}

func (cc *CartCreate) createSpec() (*Cart, *sqlgraph.CreateSpec) {
	var (
		_node = &Cart{config: cc.config}
		_spec = sqlgraph.NewCreateSpec(cart.Table, sqlgraph.NewFieldSpec(cart.FieldID, field.TypeUint64))
	)
	if id, ok := cc.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := cc.mutation.CreatedAt(); ok {
		_spec.SetField(cart.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := cc.mutation.UpdatedAt(); ok {
		_spec.SetField(cart.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := cc.mutation.Num(); ok {
		_spec.SetField(cart.FieldNum, field.TypeInt32, value)
		_node.Num = value
	}
	if value, ok := cc.mutation.MaxNum(); ok {
		_spec.SetField(cart.FieldMaxNum, field.TypeInt32, value)
		_node.MaxNum = value
	}
	if value, ok := cc.mutation.Check(); ok {
		_spec.SetField(cart.FieldCheck, field.TypeBool, value)
		_node.Check = value
	}
	if nodes := cc.mutation.UserCartIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   cart.UserCartTable,
			Columns: []string{cart.UserCartColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUint64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.UserID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := cc.mutation.ProductCartIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   cart.ProductCartTable,
			Columns: []string{cart.ProductCartColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(product.FieldID, field.TypeUint64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.ProductID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// CartCreateBulk is the builder for creating many Cart entities in bulk.
type CartCreateBulk struct {
	config
	err      error
	builders []*CartCreate
}

// Save creates the Cart entities in the database.
func (ccb *CartCreateBulk) Save(ctx context.Context) ([]*Cart, error) {
	if ccb.err != nil {
		return nil, ccb.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(ccb.builders))
	nodes := make([]*Cart, len(ccb.builders))
	mutators := make([]Mutator, len(ccb.builders))
	for i := range ccb.builders {
		func(i int, root context.Context) {
			builder := ccb.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*CartMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, ccb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, ccb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil && nodes[i].ID == 0 {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = uint64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, ccb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (ccb *CartCreateBulk) SaveX(ctx context.Context) []*Cart {
	v, err := ccb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (ccb *CartCreateBulk) Exec(ctx context.Context) error {
	_, err := ccb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (ccb *CartCreateBulk) ExecX(ctx context.Context) {
	if err := ccb.Exec(ctx); err != nil {
		panic(err)
	}
}
