// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"math"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Tracy-coder/e-mall/data/ent/predicate"
	"github.com/Tracy-coder/e-mall/data/ent/product"
	"github.com/Tracy-coder/e-mall/data/ent/productimg"
)

// ProductImgQuery is the builder for querying ProductImg entities.
type ProductImgQuery struct {
	config
	ctx         *QueryContext
	order       []productimg.OrderOption
	inters      []Interceptor
	predicates  []predicate.ProductImg
	withProduct *ProductQuery
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the ProductImgQuery builder.
func (piq *ProductImgQuery) Where(ps ...predicate.ProductImg) *ProductImgQuery {
	piq.predicates = append(piq.predicates, ps...)
	return piq
}

// Limit the number of records to be returned by this query.
func (piq *ProductImgQuery) Limit(limit int) *ProductImgQuery {
	piq.ctx.Limit = &limit
	return piq
}

// Offset to start from.
func (piq *ProductImgQuery) Offset(offset int) *ProductImgQuery {
	piq.ctx.Offset = &offset
	return piq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (piq *ProductImgQuery) Unique(unique bool) *ProductImgQuery {
	piq.ctx.Unique = &unique
	return piq
}

// Order specifies how the records should be ordered.
func (piq *ProductImgQuery) Order(o ...productimg.OrderOption) *ProductImgQuery {
	piq.order = append(piq.order, o...)
	return piq
}

// QueryProduct chains the current query on the "product" edge.
func (piq *ProductImgQuery) QueryProduct() *ProductQuery {
	query := (&ProductClient{config: piq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := piq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := piq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(productimg.Table, productimg.FieldID, selector),
			sqlgraph.To(product.Table, product.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, productimg.ProductTable, productimg.ProductColumn),
		)
		fromU = sqlgraph.SetNeighbors(piq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first ProductImg entity from the query.
// Returns a *NotFoundError when no ProductImg was found.
func (piq *ProductImgQuery) First(ctx context.Context) (*ProductImg, error) {
	nodes, err := piq.Limit(1).All(setContextOp(ctx, piq.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{productimg.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (piq *ProductImgQuery) FirstX(ctx context.Context) *ProductImg {
	node, err := piq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first ProductImg ID from the query.
// Returns a *NotFoundError when no ProductImg ID was found.
func (piq *ProductImgQuery) FirstID(ctx context.Context) (id uint64, err error) {
	var ids []uint64
	if ids, err = piq.Limit(1).IDs(setContextOp(ctx, piq.ctx, ent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{productimg.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (piq *ProductImgQuery) FirstIDX(ctx context.Context) uint64 {
	id, err := piq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single ProductImg entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one ProductImg entity is found.
// Returns a *NotFoundError when no ProductImg entities are found.
func (piq *ProductImgQuery) Only(ctx context.Context) (*ProductImg, error) {
	nodes, err := piq.Limit(2).All(setContextOp(ctx, piq.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{productimg.Label}
	default:
		return nil, &NotSingularError{productimg.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (piq *ProductImgQuery) OnlyX(ctx context.Context) *ProductImg {
	node, err := piq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only ProductImg ID in the query.
// Returns a *NotSingularError when more than one ProductImg ID is found.
// Returns a *NotFoundError when no entities are found.
func (piq *ProductImgQuery) OnlyID(ctx context.Context) (id uint64, err error) {
	var ids []uint64
	if ids, err = piq.Limit(2).IDs(setContextOp(ctx, piq.ctx, ent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{productimg.Label}
	default:
		err = &NotSingularError{productimg.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (piq *ProductImgQuery) OnlyIDX(ctx context.Context) uint64 {
	id, err := piq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of ProductImgs.
func (piq *ProductImgQuery) All(ctx context.Context) ([]*ProductImg, error) {
	ctx = setContextOp(ctx, piq.ctx, ent.OpQueryAll)
	if err := piq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*ProductImg, *ProductImgQuery]()
	return withInterceptors[[]*ProductImg](ctx, piq, qr, piq.inters)
}

// AllX is like All, but panics if an error occurs.
func (piq *ProductImgQuery) AllX(ctx context.Context) []*ProductImg {
	nodes, err := piq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of ProductImg IDs.
func (piq *ProductImgQuery) IDs(ctx context.Context) (ids []uint64, err error) {
	if piq.ctx.Unique == nil && piq.path != nil {
		piq.Unique(true)
	}
	ctx = setContextOp(ctx, piq.ctx, ent.OpQueryIDs)
	if err = piq.Select(productimg.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (piq *ProductImgQuery) IDsX(ctx context.Context) []uint64 {
	ids, err := piq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (piq *ProductImgQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, piq.ctx, ent.OpQueryCount)
	if err := piq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, piq, querierCount[*ProductImgQuery](), piq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (piq *ProductImgQuery) CountX(ctx context.Context) int {
	count, err := piq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (piq *ProductImgQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, piq.ctx, ent.OpQueryExist)
	switch _, err := piq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (piq *ProductImgQuery) ExistX(ctx context.Context) bool {
	exist, err := piq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the ProductImgQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (piq *ProductImgQuery) Clone() *ProductImgQuery {
	if piq == nil {
		return nil
	}
	return &ProductImgQuery{
		config:      piq.config,
		ctx:         piq.ctx.Clone(),
		order:       append([]productimg.OrderOption{}, piq.order...),
		inters:      append([]Interceptor{}, piq.inters...),
		predicates:  append([]predicate.ProductImg{}, piq.predicates...),
		withProduct: piq.withProduct.Clone(),
		// clone intermediate query.
		sql:  piq.sql.Clone(),
		path: piq.path,
	}
}

// WithProduct tells the query-builder to eager-load the nodes that are connected to
// the "product" edge. The optional arguments are used to configure the query builder of the edge.
func (piq *ProductImgQuery) WithProduct(opts ...func(*ProductQuery)) *ProductImgQuery {
	query := (&ProductClient{config: piq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	piq.withProduct = query
	return piq
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		CreatedAt time.Time `json:"created_at,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.ProductImg.Query().
//		GroupBy(productimg.FieldCreatedAt).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (piq *ProductImgQuery) GroupBy(field string, fields ...string) *ProductImgGroupBy {
	piq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &ProductImgGroupBy{build: piq}
	grbuild.flds = &piq.ctx.Fields
	grbuild.label = productimg.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		CreatedAt time.Time `json:"created_at,omitempty"`
//	}
//
//	client.ProductImg.Query().
//		Select(productimg.FieldCreatedAt).
//		Scan(ctx, &v)
func (piq *ProductImgQuery) Select(fields ...string) *ProductImgSelect {
	piq.ctx.Fields = append(piq.ctx.Fields, fields...)
	sbuild := &ProductImgSelect{ProductImgQuery: piq}
	sbuild.label = productimg.Label
	sbuild.flds, sbuild.scan = &piq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a ProductImgSelect configured with the given aggregations.
func (piq *ProductImgQuery) Aggregate(fns ...AggregateFunc) *ProductImgSelect {
	return piq.Select().Aggregate(fns...)
}

func (piq *ProductImgQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range piq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, piq); err != nil {
				return err
			}
		}
	}
	for _, f := range piq.ctx.Fields {
		if !productimg.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if piq.path != nil {
		prev, err := piq.path(ctx)
		if err != nil {
			return err
		}
		piq.sql = prev
	}
	return nil
}

func (piq *ProductImgQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*ProductImg, error) {
	var (
		nodes       = []*ProductImg{}
		_spec       = piq.querySpec()
		loadedTypes = [1]bool{
			piq.withProduct != nil,
		}
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*ProductImg).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &ProductImg{config: piq.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, piq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := piq.withProduct; query != nil {
		if err := piq.loadProduct(ctx, query, nodes, nil,
			func(n *ProductImg, e *Product) { n.Edges.Product = e }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (piq *ProductImgQuery) loadProduct(ctx context.Context, query *ProductQuery, nodes []*ProductImg, init func(*ProductImg), assign func(*ProductImg, *Product)) error {
	ids := make([]uint64, 0, len(nodes))
	nodeids := make(map[uint64][]*ProductImg)
	for i := range nodes {
		fk := nodes[i].ProductID
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(product.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "productID" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}

func (piq *ProductImgQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := piq.querySpec()
	_spec.Node.Columns = piq.ctx.Fields
	if len(piq.ctx.Fields) > 0 {
		_spec.Unique = piq.ctx.Unique != nil && *piq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, piq.driver, _spec)
}

func (piq *ProductImgQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(productimg.Table, productimg.Columns, sqlgraph.NewFieldSpec(productimg.FieldID, field.TypeUint64))
	_spec.From = piq.sql
	if unique := piq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if piq.path != nil {
		_spec.Unique = true
	}
	if fields := piq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, productimg.FieldID)
		for i := range fields {
			if fields[i] != productimg.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
		if piq.withProduct != nil {
			_spec.Node.AddColumnOnce(productimg.FieldProductID)
		}
	}
	if ps := piq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := piq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := piq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := piq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (piq *ProductImgQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(piq.driver.Dialect())
	t1 := builder.Table(productimg.Table)
	columns := piq.ctx.Fields
	if len(columns) == 0 {
		columns = productimg.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if piq.sql != nil {
		selector = piq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if piq.ctx.Unique != nil && *piq.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range piq.predicates {
		p(selector)
	}
	for _, p := range piq.order {
		p(selector)
	}
	if offset := piq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := piq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// ProductImgGroupBy is the group-by builder for ProductImg entities.
type ProductImgGroupBy struct {
	selector
	build *ProductImgQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (pigb *ProductImgGroupBy) Aggregate(fns ...AggregateFunc) *ProductImgGroupBy {
	pigb.fns = append(pigb.fns, fns...)
	return pigb
}

// Scan applies the selector query and scans the result into the given value.
func (pigb *ProductImgGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, pigb.build.ctx, ent.OpQueryGroupBy)
	if err := pigb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*ProductImgQuery, *ProductImgGroupBy](ctx, pigb.build, pigb, pigb.build.inters, v)
}

func (pigb *ProductImgGroupBy) sqlScan(ctx context.Context, root *ProductImgQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(pigb.fns))
	for _, fn := range pigb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*pigb.flds)+len(pigb.fns))
		for _, f := range *pigb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*pigb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := pigb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// ProductImgSelect is the builder for selecting fields of ProductImg entities.
type ProductImgSelect struct {
	*ProductImgQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (pis *ProductImgSelect) Aggregate(fns ...AggregateFunc) *ProductImgSelect {
	pis.fns = append(pis.fns, fns...)
	return pis
}

// Scan applies the selector query and scans the result into the given value.
func (pis *ProductImgSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, pis.ctx, ent.OpQuerySelect)
	if err := pis.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*ProductImgQuery, *ProductImgSelect](ctx, pis.ProductImgQuery, pis, pis.inters, v)
}

func (pis *ProductImgSelect) sqlScan(ctx context.Context, root *ProductImgQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(pis.fns))
	for _, fn := range pis.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*pis.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := pis.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
