// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Tracy-coder/e-mall/data/ent/predicate"
	"github.com/Tracy-coder/e-mall/data/ent/product"
)

// ProductUpdate is the builder for updating Product entities.
type ProductUpdate struct {
	config
	hooks    []Hook
	mutation *ProductMutation
}

// Where appends a list predicates to the ProductUpdate builder.
func (pu *ProductUpdate) Where(ps ...predicate.Product) *ProductUpdate {
	pu.mutation.Where(ps...)
	return pu
}

// SetUpdatedAt sets the "updated_at" field.
func (pu *ProductUpdate) SetUpdatedAt(t time.Time) *ProductUpdate {
	pu.mutation.SetUpdatedAt(t)
	return pu
}

// SetName sets the "name" field.
func (pu *ProductUpdate) SetName(s string) *ProductUpdate {
	pu.mutation.SetName(s)
	return pu
}

// SetNillableName sets the "name" field if the given value is not nil.
func (pu *ProductUpdate) SetNillableName(s *string) *ProductUpdate {
	if s != nil {
		pu.SetName(*s)
	}
	return pu
}

// SetCategoryID sets the "categoryID" field.
func (pu *ProductUpdate) SetCategoryID(u uint64) *ProductUpdate {
	pu.mutation.ResetCategoryID()
	pu.mutation.SetCategoryID(u)
	return pu
}

// SetNillableCategoryID sets the "categoryID" field if the given value is not nil.
func (pu *ProductUpdate) SetNillableCategoryID(u *uint64) *ProductUpdate {
	if u != nil {
		pu.SetCategoryID(*u)
	}
	return pu
}

// AddCategoryID adds u to the "categoryID" field.
func (pu *ProductUpdate) AddCategoryID(u int64) *ProductUpdate {
	pu.mutation.AddCategoryID(u)
	return pu
}

// SetTitle sets the "title" field.
func (pu *ProductUpdate) SetTitle(s string) *ProductUpdate {
	pu.mutation.SetTitle(s)
	return pu
}

// SetNillableTitle sets the "title" field if the given value is not nil.
func (pu *ProductUpdate) SetNillableTitle(s *string) *ProductUpdate {
	if s != nil {
		pu.SetTitle(*s)
	}
	return pu
}

// SetInfo sets the "info" field.
func (pu *ProductUpdate) SetInfo(s string) *ProductUpdate {
	pu.mutation.SetInfo(s)
	return pu
}

// SetNillableInfo sets the "info" field if the given value is not nil.
func (pu *ProductUpdate) SetNillableInfo(s *string) *ProductUpdate {
	if s != nil {
		pu.SetInfo(*s)
	}
	return pu
}

// SetPrice sets the "price" field.
func (pu *ProductUpdate) SetPrice(i int64) *ProductUpdate {
	pu.mutation.ResetPrice()
	pu.mutation.SetPrice(i)
	return pu
}

// SetNillablePrice sets the "price" field if the given value is not nil.
func (pu *ProductUpdate) SetNillablePrice(i *int64) *ProductUpdate {
	if i != nil {
		pu.SetPrice(*i)
	}
	return pu
}

// AddPrice adds i to the "price" field.
func (pu *ProductUpdate) AddPrice(i int64) *ProductUpdate {
	pu.mutation.AddPrice(i)
	return pu
}

// SetImgPath sets the "img_path" field.
func (pu *ProductUpdate) SetImgPath(s string) *ProductUpdate {
	pu.mutation.SetImgPath(s)
	return pu
}

// SetNillableImgPath sets the "img_path" field if the given value is not nil.
func (pu *ProductUpdate) SetNillableImgPath(s *string) *ProductUpdate {
	if s != nil {
		pu.SetImgPath(*s)
	}
	return pu
}

// SetDiscountPrice sets the "discount_price" field.
func (pu *ProductUpdate) SetDiscountPrice(i int64) *ProductUpdate {
	pu.mutation.ResetDiscountPrice()
	pu.mutation.SetDiscountPrice(i)
	return pu
}

// SetNillableDiscountPrice sets the "discount_price" field if the given value is not nil.
func (pu *ProductUpdate) SetNillableDiscountPrice(i *int64) *ProductUpdate {
	if i != nil {
		pu.SetDiscountPrice(*i)
	}
	return pu
}

// AddDiscountPrice adds i to the "discount_price" field.
func (pu *ProductUpdate) AddDiscountPrice(i int64) *ProductUpdate {
	pu.mutation.AddDiscountPrice(i)
	return pu
}

// Mutation returns the ProductMutation object of the builder.
func (pu *ProductUpdate) Mutation() *ProductMutation {
	return pu.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (pu *ProductUpdate) Save(ctx context.Context) (int, error) {
	pu.defaults()
	return withHooks(ctx, pu.sqlSave, pu.mutation, pu.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (pu *ProductUpdate) SaveX(ctx context.Context) int {
	affected, err := pu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (pu *ProductUpdate) Exec(ctx context.Context) error {
	_, err := pu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (pu *ProductUpdate) ExecX(ctx context.Context) {
	if err := pu.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (pu *ProductUpdate) defaults() {
	if _, ok := pu.mutation.UpdatedAt(); !ok {
		v := product.UpdateDefaultUpdatedAt()
		pu.mutation.SetUpdatedAt(v)
	}
}

func (pu *ProductUpdate) sqlSave(ctx context.Context) (n int, err error) {
	_spec := sqlgraph.NewUpdateSpec(product.Table, product.Columns, sqlgraph.NewFieldSpec(product.FieldID, field.TypeUint64))
	if ps := pu.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := pu.mutation.UpdatedAt(); ok {
		_spec.SetField(product.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := pu.mutation.Name(); ok {
		_spec.SetField(product.FieldName, field.TypeString, value)
	}
	if value, ok := pu.mutation.CategoryID(); ok {
		_spec.SetField(product.FieldCategoryID, field.TypeUint64, value)
	}
	if value, ok := pu.mutation.AddedCategoryID(); ok {
		_spec.AddField(product.FieldCategoryID, field.TypeUint64, value)
	}
	if value, ok := pu.mutation.Title(); ok {
		_spec.SetField(product.FieldTitle, field.TypeString, value)
	}
	if value, ok := pu.mutation.Info(); ok {
		_spec.SetField(product.FieldInfo, field.TypeString, value)
	}
	if value, ok := pu.mutation.Price(); ok {
		_spec.SetField(product.FieldPrice, field.TypeInt64, value)
	}
	if value, ok := pu.mutation.AddedPrice(); ok {
		_spec.AddField(product.FieldPrice, field.TypeInt64, value)
	}
	if value, ok := pu.mutation.ImgPath(); ok {
		_spec.SetField(product.FieldImgPath, field.TypeString, value)
	}
	if value, ok := pu.mutation.DiscountPrice(); ok {
		_spec.SetField(product.FieldDiscountPrice, field.TypeInt64, value)
	}
	if value, ok := pu.mutation.AddedDiscountPrice(); ok {
		_spec.AddField(product.FieldDiscountPrice, field.TypeInt64, value)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, pu.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{product.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	pu.mutation.done = true
	return n, nil
}

// ProductUpdateOne is the builder for updating a single Product entity.
type ProductUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *ProductMutation
}

// SetUpdatedAt sets the "updated_at" field.
func (puo *ProductUpdateOne) SetUpdatedAt(t time.Time) *ProductUpdateOne {
	puo.mutation.SetUpdatedAt(t)
	return puo
}

// SetName sets the "name" field.
func (puo *ProductUpdateOne) SetName(s string) *ProductUpdateOne {
	puo.mutation.SetName(s)
	return puo
}

// SetNillableName sets the "name" field if the given value is not nil.
func (puo *ProductUpdateOne) SetNillableName(s *string) *ProductUpdateOne {
	if s != nil {
		puo.SetName(*s)
	}
	return puo
}

// SetCategoryID sets the "categoryID" field.
func (puo *ProductUpdateOne) SetCategoryID(u uint64) *ProductUpdateOne {
	puo.mutation.ResetCategoryID()
	puo.mutation.SetCategoryID(u)
	return puo
}

// SetNillableCategoryID sets the "categoryID" field if the given value is not nil.
func (puo *ProductUpdateOne) SetNillableCategoryID(u *uint64) *ProductUpdateOne {
	if u != nil {
		puo.SetCategoryID(*u)
	}
	return puo
}

// AddCategoryID adds u to the "categoryID" field.
func (puo *ProductUpdateOne) AddCategoryID(u int64) *ProductUpdateOne {
	puo.mutation.AddCategoryID(u)
	return puo
}

// SetTitle sets the "title" field.
func (puo *ProductUpdateOne) SetTitle(s string) *ProductUpdateOne {
	puo.mutation.SetTitle(s)
	return puo
}

// SetNillableTitle sets the "title" field if the given value is not nil.
func (puo *ProductUpdateOne) SetNillableTitle(s *string) *ProductUpdateOne {
	if s != nil {
		puo.SetTitle(*s)
	}
	return puo
}

// SetInfo sets the "info" field.
func (puo *ProductUpdateOne) SetInfo(s string) *ProductUpdateOne {
	puo.mutation.SetInfo(s)
	return puo
}

// SetNillableInfo sets the "info" field if the given value is not nil.
func (puo *ProductUpdateOne) SetNillableInfo(s *string) *ProductUpdateOne {
	if s != nil {
		puo.SetInfo(*s)
	}
	return puo
}

// SetPrice sets the "price" field.
func (puo *ProductUpdateOne) SetPrice(i int64) *ProductUpdateOne {
	puo.mutation.ResetPrice()
	puo.mutation.SetPrice(i)
	return puo
}

// SetNillablePrice sets the "price" field if the given value is not nil.
func (puo *ProductUpdateOne) SetNillablePrice(i *int64) *ProductUpdateOne {
	if i != nil {
		puo.SetPrice(*i)
	}
	return puo
}

// AddPrice adds i to the "price" field.
func (puo *ProductUpdateOne) AddPrice(i int64) *ProductUpdateOne {
	puo.mutation.AddPrice(i)
	return puo
}

// SetImgPath sets the "img_path" field.
func (puo *ProductUpdateOne) SetImgPath(s string) *ProductUpdateOne {
	puo.mutation.SetImgPath(s)
	return puo
}

// SetNillableImgPath sets the "img_path" field if the given value is not nil.
func (puo *ProductUpdateOne) SetNillableImgPath(s *string) *ProductUpdateOne {
	if s != nil {
		puo.SetImgPath(*s)
	}
	return puo
}

// SetDiscountPrice sets the "discount_price" field.
func (puo *ProductUpdateOne) SetDiscountPrice(i int64) *ProductUpdateOne {
	puo.mutation.ResetDiscountPrice()
	puo.mutation.SetDiscountPrice(i)
	return puo
}

// SetNillableDiscountPrice sets the "discount_price" field if the given value is not nil.
func (puo *ProductUpdateOne) SetNillableDiscountPrice(i *int64) *ProductUpdateOne {
	if i != nil {
		puo.SetDiscountPrice(*i)
	}
	return puo
}

// AddDiscountPrice adds i to the "discount_price" field.
func (puo *ProductUpdateOne) AddDiscountPrice(i int64) *ProductUpdateOne {
	puo.mutation.AddDiscountPrice(i)
	return puo
}

// Mutation returns the ProductMutation object of the builder.
func (puo *ProductUpdateOne) Mutation() *ProductMutation {
	return puo.mutation
}

// Where appends a list predicates to the ProductUpdate builder.
func (puo *ProductUpdateOne) Where(ps ...predicate.Product) *ProductUpdateOne {
	puo.mutation.Where(ps...)
	return puo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (puo *ProductUpdateOne) Select(field string, fields ...string) *ProductUpdateOne {
	puo.fields = append([]string{field}, fields...)
	return puo
}

// Save executes the query and returns the updated Product entity.
func (puo *ProductUpdateOne) Save(ctx context.Context) (*Product, error) {
	puo.defaults()
	return withHooks(ctx, puo.sqlSave, puo.mutation, puo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (puo *ProductUpdateOne) SaveX(ctx context.Context) *Product {
	node, err := puo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (puo *ProductUpdateOne) Exec(ctx context.Context) error {
	_, err := puo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (puo *ProductUpdateOne) ExecX(ctx context.Context) {
	if err := puo.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (puo *ProductUpdateOne) defaults() {
	if _, ok := puo.mutation.UpdatedAt(); !ok {
		v := product.UpdateDefaultUpdatedAt()
		puo.mutation.SetUpdatedAt(v)
	}
}

func (puo *ProductUpdateOne) sqlSave(ctx context.Context) (_node *Product, err error) {
	_spec := sqlgraph.NewUpdateSpec(product.Table, product.Columns, sqlgraph.NewFieldSpec(product.FieldID, field.TypeUint64))
	id, ok := puo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Product.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := puo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, product.FieldID)
		for _, f := range fields {
			if !product.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != product.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := puo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := puo.mutation.UpdatedAt(); ok {
		_spec.SetField(product.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := puo.mutation.Name(); ok {
		_spec.SetField(product.FieldName, field.TypeString, value)
	}
	if value, ok := puo.mutation.CategoryID(); ok {
		_spec.SetField(product.FieldCategoryID, field.TypeUint64, value)
	}
	if value, ok := puo.mutation.AddedCategoryID(); ok {
		_spec.AddField(product.FieldCategoryID, field.TypeUint64, value)
	}
	if value, ok := puo.mutation.Title(); ok {
		_spec.SetField(product.FieldTitle, field.TypeString, value)
	}
	if value, ok := puo.mutation.Info(); ok {
		_spec.SetField(product.FieldInfo, field.TypeString, value)
	}
	if value, ok := puo.mutation.Price(); ok {
		_spec.SetField(product.FieldPrice, field.TypeInt64, value)
	}
	if value, ok := puo.mutation.AddedPrice(); ok {
		_spec.AddField(product.FieldPrice, field.TypeInt64, value)
	}
	if value, ok := puo.mutation.ImgPath(); ok {
		_spec.SetField(product.FieldImgPath, field.TypeString, value)
	}
	if value, ok := puo.mutation.DiscountPrice(); ok {
		_spec.SetField(product.FieldDiscountPrice, field.TypeInt64, value)
	}
	if value, ok := puo.mutation.AddedDiscountPrice(); ok {
		_spec.AddField(product.FieldDiscountPrice, field.TypeInt64, value)
	}
	_node = &Product{config: puo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, puo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{product.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	puo.mutation.done = true
	return _node, nil
}
