// Code generated by hertz generator.

package user

import (
	"context"

	"github.com/Tracy-coder/e-mall/biz/domain"
	"github.com/Tracy-coder/e-mall/biz/logic"
	"github.com/Tracy-coder/e-mall/biz/model/base"
	pb "github.com/Tracy-coder/e-mall/biz/model/user"
	"github.com/Tracy-coder/e-mall/data"
	"github.com/cloudwego/hertz/pkg/app"
	"github.com/cloudwego/hertz/pkg/protocol/consts"
	"github.com/jinzhu/copier"
)

// CreateProduct .
// @router /api/v2/products [POST]
func CreateProduct(ctx context.Context, c *app.RequestContext) {
	var err error
	var req pb.CreateProductReq
	resp := new(pb.CreateProductResp)
	err = c.BindAndValidate(&req)
	if err != nil {
		resp.ErrCode = base.ErrCode_ArgumentError
		resp.ErrMsg = err.Error()
		c.JSON(consts.StatusBadRequest, resp)
		return
	}
	var createProductReq domain.CreateProductReq
	err = copier.Copy(&createProductReq, &req)
	if err != nil {
		resp.ErrCode = base.ErrCode_CopierError
		resp.ErrMsg = err.Error()
		c.JSON(consts.StatusBadRequest, resp)
		return
	}
	info, err := logic.NewProduct(data.Default()).CreateProduct(ctx, createProductReq)

	if err != nil {
		resp.ErrCode = base.ErrCode_CreateProductError
		resp.ErrMsg = err.Error()
		c.JSON(consts.StatusInternalServerError, resp)
		return
	}
	productInfo := new(pb.ProductInfo)
	err = copier.Copy(productInfo, info)
	if err != nil {
		resp.ErrCode = base.ErrCode_CopierError
		resp.ErrMsg = err.Error()
		c.JSON(consts.StatusBadRequest, resp)
		return
	}
	resp.ErrCode = base.ErrCode_Success
	resp.ErrMsg = "success"
	resp.Product = productInfo
	c.JSON(consts.StatusOK, resp)
}

// ShowProduct .
// @router /api/v2/product [GET]
func ShowProduct(ctx context.Context, c *app.RequestContext) {
	var err error
	var req pb.ShowProductReq
	resp := new(pb.ShowProductResp)
	err = c.BindAndValidate(&req)
	if err != nil {
		resp.ErrCode = base.ErrCode_ArgumentError
		resp.ErrMsg = err.Error()
		c.JSON(consts.StatusBadRequest, resp)
		return
	}
	info, err := logic.NewProduct(data.Default()).ShowProduct(ctx, req.Id)

	if err != nil {
		resp.ErrCode = base.ErrCode_CreateProductError
		resp.ErrMsg = err.Error()
		return
	}
	productInfo := new(pb.ProductInfo)
	err = copier.Copy(productInfo, info)
	if err != nil {
		resp.ErrCode = base.ErrCode_CopierError
		resp.ErrMsg = err.Error()
		c.JSON(consts.StatusInternalServerError, resp)
		return
	}
	resp.ErrCode = base.ErrCode_Success
	resp.ErrMsg = "success"
	resp.Product = productInfo

	c.JSON(consts.StatusOK, resp)
}

// ListProduct .
// @router /api/v1/products [GET]
func ListProduct(ctx context.Context, c *app.RequestContext) {
	var err error
	var req pb.ListProductReq
	err = c.BindAndValidate(&req)
	resp := new(pb.ListProductResp)
	if err != nil {
		resp.ErrCode = base.ErrCode_ArgumentError
		resp.ErrMsg = err.Error()
		c.JSON(consts.StatusBadRequest, resp)
		return
	}
	var listProductReq domain.ListProductReq
	err = copier.Copy(&listProductReq, &req)
	if err != nil {
		resp.ErrCode = base.ErrCode_CopierError
		resp.ErrMsg = err.Error()
		c.JSON(consts.StatusBadRequest, resp)
		return
	}
	res, err := logic.NewProduct(data.Default()).ListProduct(ctx, listProductReq)
	if err != nil {
		resp.ErrCode = base.ErrCode_ListProductError
		resp.ErrMsg = err.Error()
		c.JSON(consts.StatusBadRequest, resp)
		return
	}
	productsInfo := make([]*pb.ProductInfo, len(res))
	err = copier.Copy(&productsInfo, &res)
	if err != nil {
		resp.ErrCode = base.ErrCode_CopierError
		resp.ErrMsg = err.Error()
		c.JSON(consts.StatusBadRequest, resp)
		return
	}
	resp.Product = productsInfo
	resp.ErrCode = base.ErrCode_Success
	resp.ErrMsg = "success"
	c.JSON(consts.StatusOK, resp)
}

// UpdateProduct .
// @router /api/v1/product [PUT]
func UpdateProduct(ctx context.Context, c *app.RequestContext) {
	var err error
	var req pb.UpdateProductReq
	resp := new(base.BaseResp)
	err = c.BindAndValidate(&req)
	if err != nil {
		resp.ErrCode = base.ErrCode_ArgumentError
		resp.ErrMsg = err.Error()
		c.JSON(consts.StatusBadRequest, resp)
		return
	}
	var updateProductReq domain.UpdateProductReq
	err = copier.Copy(&updateProductReq, &req)
	if err != nil {
		resp.ErrCode = base.ErrCode_CopierError
		resp.ErrMsg = err.Error()
		c.JSON(consts.StatusBadRequest, resp)
		return
	}
	err = logic.NewProduct(data.Default()).UpdateProduct(ctx, updateProductReq)

	if err != nil {
		resp.ErrCode = base.ErrCode_UpdateProductError
		resp.ErrMsg = err.Error()
		return
	}

	resp.ErrCode = base.ErrCode_Success
	resp.ErrMsg = "success"
	c.JSON(consts.StatusOK, resp)
}

// DeleteProduct .
// @router /api/v2/product [DELETE]
func DeleteProduct(ctx context.Context, c *app.RequestContext) {
	var err error
	var req pb.DeleteProductReq
	err = c.BindAndValidate(&req)
	resp := new(base.BaseResp)
	if err != nil {
		resp.ErrCode = base.ErrCode_ArgumentError
		resp.ErrMsg = err.Error()
		c.JSON(consts.StatusBadRequest, resp)
		return
	}
	err = logic.NewProduct(data.Default()).DeleteProduct(ctx, req.Id)

	if err != nil {
		resp.ErrCode = base.ErrCode_DeleteProductError
		resp.ErrMsg = err.Error()
		c.JSON(consts.StatusInternalServerError, resp)
		return
	}

	resp.ErrCode = base.ErrCode_Success
	resp.ErrMsg = "success"
	c.JSON(consts.StatusOK, resp)
}

// ShowProductImg .
// @router /api/v1/product/img [GET]
func ShowProductImg(ctx context.Context, c *app.RequestContext) {
	var err error
	var req pb.ShowProductImgReq
	resp := new(pb.ShowProductImgResp)
	err = c.BindAndValidate(&req)
	if err != nil {
		resp.ErrCode = base.ErrCode_ArgumentError
		resp.ErrMsg = err.Error()
		c.JSON(consts.StatusBadRequest, resp)
		return
	}
	info, err := logic.NewProduct(data.Default()).ShowProductImg(ctx, req.Id)

	if err != nil {
		resp.ErrCode = base.ErrCode_CreateProductError
		resp.ErrMsg = err.Error()
		return
	}
	productInfo := make([]*pb.ProductImg, len(info))
	err = copier.Copy(&productInfo, &info)
	if err != nil {
		resp.ErrCode = base.ErrCode_CopierError
		resp.ErrMsg = err.Error()
		c.JSON(consts.StatusInternalServerError, resp)
		return
	}
	resp.ErrCode = base.ErrCode_Success
	resp.ErrMsg = "success"
	resp.Info = productInfo

	c.JSON(consts.StatusOK, resp)
}

// CreateProductImg .
// @router /api/v2/product/img [POST]
func CreateProductImg(ctx context.Context, c *app.RequestContext) {
	var err error
	var req pb.CreateProductImgReq
	resp := new(pb.CreateProductImgResp)
	err = c.BindAndValidate(&req)
	if err != nil {
		resp.ErrCode = base.ErrCode_ArgumentError
		resp.ErrMsg = err.Error()
		c.JSON(consts.StatusBadRequest, resp)
		return
	}
	var createProductImgReq domain.CreateProductImgReq
	err = copier.Copy(&createProductImgReq, &req)
	if err != nil {
		resp.ErrCode = base.ErrCode_CopierError
		resp.ErrMsg = err.Error()
		c.JSON(consts.StatusBadRequest, resp)
		return
	}
	productImg, err := logic.NewProduct(data.Default()).CreateProductImg(ctx, createProductImgReq)
	if err != nil {
		resp.ErrCode = base.ErrCode_CreateProductImgError
		resp.ErrMsg = err.Error()
		c.JSON(consts.StatusInternalServerError, resp)
		return
	}
	productImgInfo := new(pb.ProductImg)
	err = copier.Copy(productImgInfo, productImg)
	if err != nil {
		resp.ErrCode = base.ErrCode_CopierError
		resp.ErrMsg = err.Error()
		c.JSON(consts.StatusBadRequest, resp)
		return
	}
	resp.ErrCode = base.ErrCode_Success
	resp.ErrMsg = "success"
	resp.Info = productImgInfo
	c.JSON(consts.StatusOK, resp)
}

// ShowProductRankings .
// @router /api/v1/product/rankings [GET]
func ShowProductRankings(ctx context.Context, c *app.RequestContext) {
	var err error
	var req pb.Empty
	resp := new(pb.ShowProductRankingsResp)
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}
	res, err := logic.NewProduct(data.Default()).ShowProductRankings(ctx)
	if err != nil {
		resp.ErrCode = base.ErrCode_ListProductError
		resp.ErrMsg = err.Error()
		c.JSON(consts.StatusBadRequest, resp)
		return
	}
	productsInfo := make([]*pb.ProductInfo, len(res))
	err = copier.Copy(&productsInfo, &res)
	if err != nil {
		resp.ErrCode = base.ErrCode_CopierError
		resp.ErrMsg = err.Error()
		c.JSON(consts.StatusBadRequest, resp)
		return
	}
	resp.Info = productsInfo
	resp.ErrCode = base.ErrCode_Success
	resp.ErrMsg = "success"
	c.JSON(consts.StatusOK, resp)
}
